### ISSUE TITLE
Explore AWS Elastic File System for OSP workers?

### ISSUE THREAD

**Issue by davidmcclure** [overview/osp#3]
Right now, the OSP workers interact with the corpus via EBS volumes. Eg, if we spin up N workers, we make N volumes from the master snapshot, and mount a separate volume on each individual worker. When the workers need to pool data (eg, when saving citation results), they connect to a central database server and write the rows. This works, but involves some tricky code and server provisioning.

But, AWS recently released a new product called [Elastic File System](https://aws.amazon.com/efs/) - a virtual file system that can be shared among multiple EC2 instances. This could be an attractive alternative? I don't know enough about it to say for sure, but I think it's worth looking into, because, if it works the way I hope, it could make the startup / collaboration / maintenance workflow quite a bit simpler.

cc @elotroalex

**Comment by adamhooper** [comment]
I looked into EFS. It's an implementation of NFS, so it might be what you're looking for. As long as the different machines don't try to write to the same filenames at the same time, it's a great option.

Unfortunately, it costs 3x what normal SSD storage would cost on EBS, and 6x what magnetic storage would cost. And it doesn't have snapshots.

When planning things out, compare EFS to a t2.micro with NFS installed and an EBS volume. That EBS solution would have a fixed cost, and it would be slower than EFS. For a certain size of project (in the 100s of GBs, I'm guessing), the t2.micro will be cheaper.

You'd need to program your own NFS-mounting scripts with the EBS solution, but you'd need to program your own backup scripts with the EFS solution, so it seems to me the programming effort will be the same no matter what.

And I don't think you were proposing this, but to be on the safe side I'll say it now: you can't run Postgres over NFS.
